-- The ratification debate joins the post. GENERATED by
-- scripts/generate-debate-migration.mjs from workers/post/content/debate.json;
-- regenerate rather than editing the CASE table by hand.

-- 1. Deliveries widen to the shared id space: 1-85 Publius, 101-116 Brutus,
--    151-166 Cato. SQLite CHECK constraints are immutable, so rebuild the
--    table, preserving rows, ids, the exactly-once UNIQUE, and the index.
CREATE TABLE deliveries_debate (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subscriber_id INTEGER NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
  paper_number INTEGER NOT NULL CHECK (
    paper_number BETWEEN 1 AND 85
    OR paper_number BETWEEN 101 AND 116
    OR paper_number BETWEEN 151 AND 166
  ),
  scheduled_for TEXT NOT NULL,                 -- ISO date; UNIQUE below = exactly-once
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'sent', 'bounced', 'failed')),
  provider_message_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (subscriber_id, paper_number, scheduled_for)
);

INSERT INTO deliveries_debate (id, subscriber_id, paper_number, scheduled_for, status, provider_message_id, created_at)
  SELECT id, subscriber_id, paper_number, scheduled_for, status, provider_message_id, created_at
  FROM deliveries;

DROP TABLE deliveries;
ALTER TABLE deliveries_debate RENAME TO deliveries;
CREATE INDEX idx_deliveries_status ON deliveries (status, created_at);

-- 2. Weekly subscribers who are mid-course owe one make-up email covering the
--    essays that ran before the point they have reached. Calendar subscribers
--    are untouched.
ALTER TABLE subscribers ADD COLUMN makeup_pending INTEGER NOT NULL DEFAULT 0;

UPDATE subscribers SET makeup_pending = 1
WHERE program = 'weekly' AND progress_index > 0;

-- 3. Weekly progress_index changes meaning: "last paper number sent" becomes
--    "count of merged debate items consumed" (new = merged position of the old
--    paper + 1). Zero stays zero; calendar subscribers never used progress.
UPDATE subscribers SET progress_index = CASE progress_index
  WHEN 1 THEN 2
  WHEN 2 THEN 3
  WHEN 3 THEN 5
  WHEN 4 THEN 6
  WHEN 5 THEN 8
  WHEN 6 THEN 9
  WHEN 7 THEN 10
  WHEN 8 THEN 11
  WHEN 9 THEN 12
  WHEN 10 THEN 13
  WHEN 11 THEN 14
  WHEN 12 THEN 15
  WHEN 13 THEN 16
  WHEN 14 THEN 18
  WHEN 15 THEN 19
  WHEN 16 THEN 20
  WHEN 17 THEN 21
  WHEN 18 THEN 22
  WHEN 19 THEN 23
  WHEN 20 THEN 24
  WHEN 21 THEN 25
  WHEN 22 THEN 26
  WHEN 23 THEN 27
  WHEN 24 THEN 28
  WHEN 25 THEN 29
  WHEN 26 THEN 30
  WHEN 27 THEN 31
  WHEN 28 THEN 32
  WHEN 29 THEN 33
  WHEN 30 THEN 34
  WHEN 31 THEN 35
  WHEN 32 THEN 36
  WHEN 33 THEN 37
  WHEN 34 THEN 38
  WHEN 35 THEN 39
  WHEN 36 THEN 40
  WHEN 37 THEN 42
  WHEN 38 THEN 43
  WHEN 39 THEN 44
  WHEN 40 THEN 45
  WHEN 41 THEN 46
  WHEN 42 THEN 47
  WHEN 43 THEN 48
  WHEN 44 THEN 50
  WHEN 45 THEN 51
  WHEN 46 THEN 52
  WHEN 47 THEN 53
  WHEN 48 THEN 54
  WHEN 49 THEN 55
  WHEN 50 THEN 56
  WHEN 51 THEN 57
  WHEN 52 THEN 59
  WHEN 53 THEN 60
  WHEN 54 THEN 61
  WHEN 55 THEN 62
  WHEN 56 THEN 63
  WHEN 57 THEN 64
  WHEN 58 THEN 65
  WHEN 59 THEN 66
  WHEN 60 THEN 67
  WHEN 61 THEN 68
  WHEN 62 THEN 69
  WHEN 63 THEN 70
  WHEN 64 THEN 71
  WHEN 65 THEN 72
  WHEN 66 THEN 73
  WHEN 67 THEN 74
  WHEN 68 THEN 75
  WHEN 69 THEN 76
  WHEN 70 THEN 77
  WHEN 71 THEN 78
  WHEN 72 THEN 79
  WHEN 73 THEN 81
  WHEN 74 THEN 82
  WHEN 75 THEN 83
  WHEN 76 THEN 84
  WHEN 77 THEN 85
  WHEN 78 THEN 86
  WHEN 79 THEN 87
  WHEN 80 THEN 88
  WHEN 81 THEN 89
  WHEN 82 THEN 90
  WHEN 83 THEN 91
  WHEN 84 THEN 92
  WHEN 85 THEN 93
  ELSE progress_index
END
WHERE program = 'weekly' AND progress_index > 0;
